package com.taskflow.enums;

public enum ActivityAction {
    USER_REGISTERED,
    USER_LOGIN,
    USER_LOGOUT,
    USER_UPDATED,
    USER_DELETED,
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_DELETED,
    PROJECT_STATUS_CHANGED,
    TASK_CREATED,
    TASK_UPDATED,
    TASK_COMPLETED,
    TASK_DELETED,
    COMMENT_ADDED,
    FILE_UPLOADED,
    SYSTEM_INITIALIZATION
}
