package com.taskflow.enums;

public enum SecurityEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    OTP_SENT,
    OTP_VERIFIED,
    EMAIL_VERIFIED,
    REFRESH_TOKEN_ROTATED,
    REFRESH_TOKEN_REVOKED,
    SESSION_REVOKED,
    ALL_SESSIONS_REVOKED
}
